### ISSUE TITLE
multiselect delete on Products not working 

### ISSUE THREAD

**Issue by LuckyDude68** [bagisto/bagisto#4266] opened 2020-11-17 23:12 UTC
# Bug report

### Title
multiselect delete on Products not working 

### Issue Description
When trying to delete Products selected with the multiselect tool I get a 500 error.

### Preconditions
v1.2.0
up to date till commit 130ae68d3

### Steps to reproduce
![Screenshot 2020-11-17 at 23 19 47](https://user-images.githubusercontent.com/73575652/99461445-24f3e780-2932-11eb-9786-a4343e6d177a.png)

### Expected result
Selected Products should be deleted

### Actual result
500-Error
![Screenshot 2020-11-17 at 23 20 04](https://user-images.githubusercontent.com/73575652/99461467-2d4c2280-2932-11eb-8bf6-7a313c239452.png)

**Comment by bhanu-webkul** [comment] 2020-11-18 04:39
@LuckyDude68 
unable to reproduce this issue in master- https://prnt.sc/vl736s

**Comment by devansh-webkul** [comment] 2020-11-19 08:13
@ghermans,

Did you reproduce that bug, can you please share the steps so that I can fix it.

**Comment by vaishaliwebkul** [comment] 2020-11-20 16:14
@LuckyDude68 
set app_debug = true for your application inside .env then show us the exact error in development mode.

**Comment by ghermans** [comment] 2020-11-20 16:30
@devansh-webkul @vaishaliwebkul @LuckyDude68 it is working fine in the master branch.

**Comment by vaishaliwebkul** [comment] 2020-11-24 05:53
@LuckyDude68 
closing as this bug does not exist.

**Closed by vaishaliwebkul** 2020-11-24 05:53 UTC
Labels: Question
