### ISSUE TITLE
issue while selecting quantity more than 1 on buy now

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#850] opened 2019-04-18 12:55 UTC
on the product page, there should be an **increase-decrease** option for **quantity** so that user can select a quantity and click on buy now, so it will be redirected on shipping page with selected quantity!!!!!

**Comment by prashant-webkul** [comment] 2019-04-18 14:10
This is a duplicate of already closed issue https://github.com/bagisto/bagisto/issues/197

**Comment by jyoti-webkul** [comment] 2019-04-26 14:40
Framework Version: 0.1.5
Not fixed

**Comment by jyoti-webkul** [comment] 2019-06-07 09:30
- Framework Version: 0.1.5

Fixed

**Comment by jyoti-webkul** [comment] 2019-08-08 12:12
- Framework Version: 0.1.6

------------------------------------------
Again getting this issue

**Comment by bhanu-webkul** [comment] 2019-09-10 05:24
Framework Version: 0.1.6

Still same issue

**Comment by bhanu-webkul** [comment] 2019-10-11 09:30
Framework Version: 0.1.8

issue fixed

**Closed by bhanu-webkul** 2019-10-11 09:30 UTC
Labels: Bug fixed, Enhancement
