### ISSUE TITLE
Class NumberFormatter not found after installation

### ISSUE THREAD

**Issue by ArsalanSiddique** [bagisto/bagisto#8594] opened 2023-10-03 20:33 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.5.1

### Issue Description

I've installed the PHP intl extension and checked using

```
PHP -m
``` 
command, it is successfully installed but not working on my Ubuntu 20.04

### Preconditions

OS: Ubuntu 20.04
PHP 8.1

### Steps to reproduce

Just install fresh Bagisto and login to the admin dashboard

### Expected Result

It should be login successfully

### Actual Result

Getting error
Class NumberFormatter not found.

ss attached

### Screenshots

![Screenshot from 2023-10-03 23-40-13.png](https://forums.bagisto.com/assets/uploads/files/1696358466572-screenshot-from-2023-10-03-23-40-13.png)

**Comment by jitendra-webkul** [comment] 2023-10-04 04:30
Install Intl extension, refer to the following issues for more info

Duplicate of #6218, #6050, #4012

**Closed** 2023-10-04 05:57 UTC
Labels: Bug
