### ISSUE TITLE
Sometimes photos removing

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9812] opened 2024-05-17 11:02 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.x.dev

### Issue Description

Sometimes photos after saving are removed from the Product. It was twice but after I couldn't repeat it to understand the reason why.

### Preconditions

No one product.

### Steps to reproduce

Add the photo to the Product and Save. - Everything is fine.
Add one more photo to the Product and Save. - The first photo was removed.
Add one more photo to the Product and Save. - The first photo was removed again.
Add one more photo to the Product and Save. - Everything is fine again.
It was with 2 products in a row but the photos for the third product are OK.

### Expected Result

All added photos are saved.

### Actual Result

Some photos were removed

### Additional context

In continuing the closed task https://github.com/bagisto/bagisto/issues/9800
I have checked the latest code and the issue is still there.

**Comment by jitendra-webkul** [comment] 2024-05-20 10:24
Could you please share a video demonstrating the issue? I have checked but am unable to reproduce it on my end.

**Comment by jitendra-webkul** [comment] 2024-05-22 05:19
Closing this issue as fixed in master branch

**Closed by jitendra-webkul** 2024-05-22 05:19 UTC
Labels: Bug
