### ISSUE TITLE
Write Table migrations with utf8mb4 as default charset

### ISSUE THREAD

**Issue by nickezekias** [bagisto/bagisto#4945] opened 2021-06-20 19:40 UTC
# Bug report

### Issue Description

Collation problems when linking categories to root category
"SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update categoriesset_lft= case when_lft>= 14 then_lft+2 else _lftend,_rgt= case when_rgt>= 14 then_rgt+2 else _rgt end where (_lft>= 14 or_rgt >= 14))

### Preconditions

mysql: Ver 15.1 Distrib 10.5.9-MariaDB
Os: Kali GNU/Linux Rolling
OS Type:  64-bit
Distributor:  Debian
CPU: Intel Core i3-4005U @ 1.70GHz x 4

#### Bagisto version
- [ ] master branch 
- [ ] 1.3.1
I tested on both
### Steps to reproduce

On a fresh bagisto installation
1. Open Admin Panel and add new category while checking Root as parent category
2. Update existing category and set Root as parent category

### Expected result

The parent of the category should be set to Root

### Actual result

Below error is returned: 
Collation problems when linking categories to root category
"SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update categoriesset_lft= case when_lft>= 14 then_lft+2 else _lftend,_rgt= case when_rgt>= 14 then_rgt+2 else _rgt end where (_lft>= 14 or_rgt >= 14))

**Comment by devansh-webkul** [comment] 2021-06-21 04:55
Hi @ghermans,

 `utf8mb4_unicode_ci` is mostly used worldwide. I  personally feel this should be in the core.

**Comment by devansh-webkul** [comment] 2021-08-16 05:47
Hi @nickezekias and @ghermans,

- This is strange earlier it was reproducible now it is not reproducible. I just checked in my instance with MYSQL 8.0,

    ![Screenshot(2)](https://user-images.githubusercontent.com/68321766/129516553-42960cbb-81ed-4df3-b310-8e352c29c768.png)

- So I thought it may be an issue in an earlier version, so I tested this with MYSQL 5.7 also,

    ![Screenshot(1)](https://user-images.githubusercontent.com/68321766/129516629-3eda94c6-e6f4-4d45-b351-7b38d9e39cba.png)

- I am not getting errors in the latest master.
   
    ![Screenshot(3)](https://user-images.githubusercontent.com/68321766/129516732-eea637b4-49be-4a2d-8a6c-da97a046d810.png)

- If you are able to reproduce this in master then let me know.

**Comment by devansh-webkul** [comment] 2021-09-13 07:29
Hi @nickezekias,

Any feedback on the above reply because I need to know.

**Comment by devansh-webkul** [comment] 2021-09-23 13:05
Not getting any revert from last 10 days. I am closing this.

Review this comment before opening issue,
https://github.com/bagisto/bagisto/issues/4945#issuecomment-899240087

**Closed by devansh-webkul** 2021-09-23 13:05 UTC
Labels: Optimization
