### ISSUE TITLE
Catalog sale based on category doesn't work for variable products.

### ISSUE THREAD

**Issue by Dunicotech** [bagisto/bagisto#9721] opened 2024-04-26 15:24 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.1.1

### Issue Description

When adding catalog discount rules for specific categories. Variable products within the selected category don't get the discount. If the main product has the selected category nothing happens. If the variation has the specific category the price goes to 0.

### Preconditions

Bagisto V2.1.1. with variable products.

### Steps to reproduce

1. Go to 'marketing -> promotions -> catalog rules -> create rule'
2. Click on 'Create catalog rule -> add categorie as condition -> add contains -> select a categorie with a variable product in it'
3. Go to the front-end and add the product to the cart.

### Expected Result

Sale price shown on the product page and in the card.

### Actual Result

Price goes to 0 or the price doesn't change at all.

**Comment by ashishkumar-webkul** [comment] 2024-04-29 08:24
@Dunicotech 

As I have checked the concern and was unable to reproduce such issue, could you please assist me by providing a video or step-by-step instructions to reproduce it? This will help me understand the issue in more detail. I have checked the same in V2.1.1

For now you can check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/c5ba3b23-f7cf-4619-807d-24711ce57879

**Comment by Dunicotech** [comment] 2024-04-29 15:43
Hi,

Thanks for the reply. Here's a video of my result: https://www.loom.com/share/d5880399643944b08300870f16e793b9?sid=30d7ae6e-ff65-4f08-8ec0-17a5200e70e5

**Comment by Dunicotech** [comment] 2024-05-01 11:33
I'd like to add that there are 2 issues present:
1. The discount change the product price when 1 item is purchased
2. The Product price goes to zero after adding a product several times.

**Comment by ashishkumar-webkul** [comment] 2024-05-08 14:00
@Dunicotech

Hello,

Thank you for your patience. We have thoroughly investigated the issue you raised, but we were unable to replicate it. Attached is a video demonstrating our findings.

Could you please provide further details about your concern so that we can better understand the issue and work towards resolving it?

Your input is invaluable to us.

Thank you.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/afb5c91d-d567-45f7-86aa-296773f9bcf0

**Closed** 2024-05-14 05:49 UTC
Labels: Bug, Need More Info
