### ISSUE TITLE
Tax is added to total price, even when catalog prices are including tax

### ISSUE THREAD

**Issue by arne-s** [bagisto/bagisto#9585] opened 2024-03-10 15:21 UTC
**Describe the bug**
In my catalog all the prices are including tax, so I set the option "Tax inclusive" to true in the admin

But on the checkout and on the invoices it adds the tax to the total price, which shouldn't happen because the tax is already part of the product price. 

**To Reproduce**
- Set the option "Tax inclusive" to true
- Create a product, set the price to $10,00
- Set the Tax category for this product to 10%

**Expected behavior**
This should be the pricing:

Product: $10,00
Tax: $1,00
Total: $10,00

But instead I get this :

Product: $10,00
Tax: $1,00
Total: $11,00

**Additional context**
I'm using Bagisto 2.1.1

**Comment by ashishkumar-webkul** [comment] 2024-03-13 07:56
@arne-s 

Thank You So much for your query, we really appreciate your contribution towards bagisto.

As per checking the concern it was found that the issue is appearing. Please check the video for reference and confirm once.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/26331421-0628-4590-afb0-08b6af75b1f7

**Comment by jitendra-webkul** [comment] 2024-04-18 11:16
This issue will be resolved in version 2.2.0.

**Comment by jitendra-webkul** [comment] 2024-04-30 06:27
Fixed on #9711

**Closed** 2024-05-09 10:44 UTC
Labels: Bug
