### ISSUE TITLE
Issue when category slug & product slug are same

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2619] opened 2020-03-05 12:21 UTC
# Bug report

### Title
An application couldn't specify the different URL when the product slug & category slug are the same.

### Issue Description
Getting category page when click on any product, as both category & product slug are same

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- put the same slug in both category and product
    2. step2-  next, click to the product image in the shop view

### Expected result

* when we mention the same slug, then redirect URL should different.  

### Actual result

>  
![Screenshot(1)](https://user-images.githubusercontent.com/43210406/75981140-e20bf400-5f09-11ea-9014-89e9e4b2f8e9.png)

![Screenshot(2)](https://user-images.githubusercontent.com/43210406/75981155-e9330200-5f09-11ea-90de-79128849c739.png)

![Screenshot(3)](https://user-images.githubusercontent.com/43210406/75981161-ee904c80-5f09-11ea-8b04-355d9ec7b706.png)

**Comment by AnnikaWolff** [comment] 2020-03-06 09:13
Dear @vaishaliwebkul 

please excuse my contradiction: This is not a bug, it is just a question of configuration.

When a product or category link is clicked, the system has to determine, where the URL should direct to. And first, it has a look at all category slugs. If no category with the slug defined in the URL could be found, the system searches a product with that slug. 
In the present case with a product and a category sharing the same slug, the system always will direct to the category. Something has to win the debate, and it is the category.

To prevent categories and products from sharing the same slug, one could add new validation rules: Before storing any slug, it could be checked in both, categories and products, for that slug to be unique. You possibly may open an according issue?

Anyhow, for good reasons, slugs can be changed by admins. For now, I propose to change one of the slugs, e.g. to "t-shirt" with a dash, or to "T-Shirts" for the category.

Best regards,
Annika

**Closed** 2020-03-18 09:19 UTC
Labels: Core, Not an Issue

**Comment by emperorjm** [comment] 2020-04-04 20:02
This is definitely a bug and the reasoning above does not make much sense. Seeing that both Category Slugs and Product URLs are both fighting for the same root path there should be a check done to make sure both cannot be the same as the first occurrence will win (In this case the category slug). A user/admin should not have to wait until this happens to know that there is a conflict.

To prevent this, the core solution should give either the product or category a sub-path (product/{url} or category/{slug}) to prevent such a case.

A more SEO friendly solution should be implemented to allow for both packages to use the root path once the path is available. This should also allow other packages to utilize the root path as well they can tap into the validator to know whether or not the URL path is available.
