### ISSUE TITLE
Frontend Currency Symbol Not Showing Instead the currency CODE

### ISSUE THREAD

**Issue by knif3rdev** [bagisto/bagisto#4005] opened 2020-10-05 12:03 UTC
Version: Master (1.2.0)
On my dashboard currency symbol showing fine
https://prnt.sc/utfaza
 , while on the frontend instead of currency symbol It shows the currency code.

https://prnt.sc/utfc06

While changing to USD the currency symbol will display correctly. But I need to display it with currency symbol which is P the code is PHP as Philippine Peso

**Comment by devansh-webkul** [comment] 2020-10-06 08:02
Hi @knif3rdev,

The problem is with the locale. Well, I am able to achieve this without any coding. Did you setup your locale as well. Because currency is also dependent on locale.

![Screenshot from 2020-10-06 13-29-56](https://user-images.githubusercontent.com/68321766/95174710-11ece400-07d8-11eb-8db0-a99592ff8733.png)

**Comment by knif3rdev** [comment] 2020-10-06 08:21
oh, nope, I only setup locale currency .. let me try adding it. Thanks for the info.

**Comment by knif3rdev** [comment] 2020-10-06 08:23
What did you put in the code? is it en_PH ? or PH alone?

**Comment by devansh-webkul** [comment] 2020-10-06 08:26
It' s `tl_ph`.

**Comment by knif3rdev** [comment] 2020-10-06 08:32
I already added, it seems it didn't work

https://prnt.sc/utxpir

still I got the PHP code 

I did the php artisan config:cache and even clear it and view clear. it didn't work 

Can you make a screenshot ? in the locale.

**Comment by devansh-webkul** [comment] 2020-10-06 08:34
Did you add this locale to your channel?

**Comment by knif3rdev** [comment] 2020-10-06 08:39
<img width="1347" alt="Screenshot at Oct 06 16-38-42" src="https://user-images.githubusercontent.com/34658417/95178805-6ef59380-07f2-11eb-9f37-794bb57271e7.png">

Do I need to check Filipino for locales?

**Comment by devansh-webkul** [comment] 2020-10-06 08:42
Here, everything is fine. Now check the catalog section. You need to fill the form for that locale as well.

**Comment by knif3rdev** [comment] 2020-10-06 08:50
oh, I got it. it needs to be selected my locale, thank you very much @devansh-webkul .  catalog and slider everything :) LOLz ..

**Comment by ghermans** [comment] 2020-10-06 08:59
Nice to see that your problem has been resolved.
I will close this issue report, if the problem still pops up please let us know.

**Closed by ghermans** 2020-10-06 08:59 UTC
Labels: help wanted

**Comment by knif3rdev** [comment] 2020-10-06 10:35
I thought it will fix the special price issue 

https://scontent.fceb2-1.fna.fbcdn.net/v/t1.15752-9/120727452_377799053400662_1034286605282061174_n.jpg?_nc_cat=106&_nc_sid=ae9488&_nc_ohc=-sd_C7aK58UAX_qagTd&_nc_oc=AQkmmEbiymYtPZOmtGqiY1c5DMYpTGEXLnacRcRLVnIPzTWIeTlBaC-0RVt0yaQ0dV3NlhkD2ncMExVoC9w53-R4&_nc_ht=scontent.fceb2-1.fna&oh=4d415d4f6cca946c0ed3f31dd1a793d2&oe=5FA222B0

**Comment by knif3rdev** [comment] 2020-10-06 10:43
in desktop mode it's ok. 
<img width="1443" alt="Screenshot at Oct 06 18-42-27" src="https://user-images.githubusercontent.com/34658417/95191718-b59fb980-0803-11eb-8a36-5cc51f362f57.png">

**Comment by devansh-webkul** [comment] 2020-10-06 11:09
Hi @knif3rdev,

Well, this is a different  issue and we are working on it.

**Comment by roham96** [comment] 2020-10-11 23:31
> Version: Master (1.2.0)
> On my dashboard currency symbol showing fine
> https://prnt.sc/utfaza
> , while on the frontend instead of currency symbol It shows the currency code.
> 
> https://prnt.sc/utfc06
> 
> While changing to USD the currency symbol will display correctly. But I need to display it with currency symbol which is P the code is PHP as Philippine Peso

hi,

package -> webkul -> Core -> src -> core.php

convert formatPrice function to this :100: 

  public function formatPrice($price, $currencyCode)
    {
        if (is_null($price))
            $price = 0;


        $formater = new \NumberFormatter(app()->getLocale(), \NumberFormatter::CURRENCY);

        if ($symbol = $this->getCurrentCurrency()->symbol) {
            if ($this->currencySymbol($this->getCurrentCurrencyCode()) == $symbol) {
                return $formater->formatCurrency($price, $this->getCurrentCurrencyCode());
            } else {
                $formater->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, $symbol);

                return $formater->format($this->convertPrice($price));
            }
        } else {
            return $formater->formatCurrency($price, $this->getCurrentCurrencyCode());
        }
    }
