### ISSUE TITLE
Errors when delete option of attribute "color"

### ISSUE THREAD

**Issue by nguyenthanhtuanIT** [bagisto/bagisto#3980] opened 2020-09-29 04:31 UTC
# Bug report

### Title
Errors when delete option of attribute "color" with Swatch Type as **Color swatch**

### Issue Description
When edit attribute color, we selected **Swatch Type is Color swatch**, then we deleted a option and the returned result is mixed 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. version:  1.2
### Steps to reproduce

    1. step-1: select swatch Type is color swatch 
    2. step-2 : add color for options
    3. step-3: delete a option
First, I have attribute color with options

![image](https://user-images.githubusercontent.com/35143673/94513168-32e98e00-0248-11eb-881b-67d9cd8bbe03.png)

Final, I deleted option "white".
### Expected result
**Tell us what should happen.**

![Screenshot from 2020-09-29 11-33-35](https://user-images.githubusercontent.com/35143673/94513008-cc647000-0247-11eb-875f-c825bcf546ca.png)

### Actual result

![image](https://user-images.githubusercontent.com/35143673/94513231-63312c80-0248-11eb-8d2d-b5557bc12c9a.png)

**Comment by devansh-webkul** [comment] 2020-09-29 05:49
@bhanu-webkul I am not able to reproduce that. Can you show us the steps to reproduce how he reproduce that bug?

Because currently, we are not doing the realtime saving.

**Comment by devansh-webkul** [comment] 2020-09-29 06:02
@bhanu-webkul OK I got it. Its a bug.

**Comment by bhanu-webkul** [comment] 2020-09-29 06:03
@devansh-webkul , errors which he has mentioned does not mean any exception is there, simply when admin is deleting any option the values are getting deleted but the selected swatch color doesn't get deleted. As you can see in steps to reproduces, there is one white color swatch and one blue  so when admin delete white one,then options of blue get shifted to white color swatch.
I hope you got the point

**Comment by vaishaliwebkul** [comment] 2020-10-08 13:37
@nguyenthanhtuanIT 
this bug is fixed now, please check.

Feel free to reopen the issue anytime.

**Closed by vaishaliwebkul** 2020-10-08 13:37 UTC
Labels: Bug, Bug Fixed, HACKTOBERFEST
