### ISSUE TITLE
address and review are not deleted

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#4999] opened 2021-07-08 09:56 UTC
the incoming update also redirects the delete buttons to the 404 page and does not delete the review, the address is not deleted

**Comment by devansh-webkul** [comment] 2021-07-08 09:59
Hi @Arsivpro,

This is because the route method has been changed and your changes are cached. Just try to clear your routes cache,

**Comment by Arsivpro** [comment] 2021-07-08 10:16
clear cache and reinstall artisan route:cache same problem persists

**Comment by Arsivpro** [comment] 2021-07-08 10:50
It works as I want when I get the route address and delete the route made in the review.

**Comment by ghermans** [comment] 2021-07-08 10:55
What version are you using?

**Comment by Arsivpro** [comment] 2021-07-08 10:58
@ghermans latest version

**Comment by ghermans** [comment] 2021-07-08 11:01
Do you mean 1.3.1 from composer , or did you cloned the master branch?

**Comment by Arsivpro** [comment] 2021-07-08 11:02
@ghermans I am using bagisto 1.3.

**Comment by devansh-webkul** [comment] 2021-07-08 11:31
Hi @Arsivpro,

If you have taken the latest clone, then make sure you check the views also. Because implementation is also done in the view portion also.

So if you have not customized then make sure you run `vendor:publish` command or else do it manually.

**Comment by devansh-webkul** [comment] 2021-07-09 04:05
@Arsivpro and @ghermans,

I am closing this as this is not reproducible in the master branch. There is some implementation missing by @Arsivpro.

**Closed by devansh-webkul** 2021-07-09 04:05 UTC
Labels: Help Wanted, Not An Issue
