### ISSUE TITLE
Doesn't work Social login with Google

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9828] opened 2024-05-21 18:59 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

Doesn't work:
Social login

### Preconditions

By [instruction](https://devdocs.bagisto.com/1.x/user-guides/social-auth.html#configuring-google)

### Steps to reproduce

![image](https://github.com/bagisto/bagisto/assets/9464550/cb7d0212-f539-4ba2-aa0c-ef6fe573d486)
https://_hiddenwebsite_.com/customer/social-login/google/callback

### Expected Result

Login to Shop

### Actual Result

The Login page just reloading

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/9464550/93c371dc-bc61-4ea5-a87d-f179bad42af3)
![image](https://github.com/bagisto/bagisto/assets/9464550/f0e380dd-9b96-4768-9c99-187798560f5f)
![image](https://github.com/bagisto/bagisto/assets/9464550/a5465879-d41f-48eb-b78b-c05fe26a22af)

### Additional context

I also can't run Facebook but maybe I did something wrong, recheck it on your side.

**Comment by suraj-webkul** [comment] 2024-05-22 10:26
Hi @plyaskin,

We have reviewed the social login functionalities and confirmed that they are all working fine except for LinkedIn. The issue with LinkedIn was due to a change in their callback URL. This has now been resolved with the [following PR](https://github.com/bagisto/bagisto/pull/9831/commits/a37819da1984d29d7b9c50a8f6b795ea22b7635c).

**Closed** 2024-05-27 10:26 UTC
Labels: Bug, Bug Fixed
