### ISSUE TITLE
Bagisto Installer Error - PDOConnection.php line 70

### ISSUE THREAD

**Issue by samox1n** [bagisto/bagisto#4790] opened 2021-04-09 21:59 UTC
Bagisto Installer Error

Log
Configuration cache cleared!Configuration cached successfully!In PDOConnection.php line 70:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatib  le with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchMo  deArgs)

bagisto-1.3.1

nginx
mysql
php7.4
ubuntu 16.04

**Comment by devansh-webkul** [comment] 2021-04-12 04:03
Hi @samox1n,

Can you share the PHP version?

Not the one which is showing in the terminal the one which is linked with Nginx. Because this issue seems to be version-specific.

Just share the screenshot of  the below code,

~~~php
<?php

phpinfo();
~~~

**Comment by samox1n** [comment] 2021-04-12 11:49
Core
PHP Version 7.4.16

**Comment by devansh-webkul** [comment] 2021-04-12 12:33
Hi @samox1n,

I am not able to reproduce this in PHP 7.4 with Nginx.

Please check whether Nginx is connected with the mentioned version.

The issue which you have mentioned is specific to PHP version 8. Please setup environment according to these requirements,
https://devdocs.bagisto.com/1.x/introduction/requirements.html#server-configuration

**Comment by devansh-webkul** [comment] 2021-04-15 09:40
Hi @samox1n,

Closing this as this is not an issue. For discussion, you can post  this in the Bagisto forum,
https://forums.bagisto.com/

**Closed by devansh-webkul** 2021-04-15 09:40 UTC
Labels: Question
