### ISSUE TITLE
When editing the currency, there is no proper validation in the code field.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9401] opened 2024-02-02 06:28 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When editing the currency code to less than three letters, the code is saved without any error. In this case, if the currency symbol is not specified, the price of any product is not displayed on the shop.

### Preconditions

- Create currency from admin.
- Use that currency in the current channel.

### Steps to reproduce

1. Go to admin > settings > currencies.
2. Edit the currency that is available in the shop and select that in shop .
3. Save currency code with less than 3 letters and do not use currency symbol.
4. See error in shop

### Expected Result

Currency code less than 3 characters should not be saved, validation error should occur.

### Actual Result

When editing the currency code to less than three letters, the code is saved without any error. In this case, if the currency symbol is not specified, the price of any product is not displayed on the shop.

**Comment by ashishkumar-webkul** [comment] 2024-02-02 07:43
@amit-webkul 

Checked and Found that the issue is appearing. Please fix the issue. 

**Video**


https://github.com/bagisto/bagisto/assets/92721837/4629be38-057f-40db-be2b-b4d379d5f43f

**Comment by ashishkumar-webkul** [comment] 2024-02-05 05:20
@amit-webkul

Checked and Found that the issue has been fixed and validation has been added. Please find the screenshot [here](https://prnt.sc/JefcWDDCgvHa)

**Comment by ashishkumar-webkul** [comment] 2024-02-06 11:36
Checked and FOund that the  issue has been fixed and PR has been merged. Hence I am closing the issue from here, please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/3d389a82-73d5-491f-9add-54b086b6cf50

**Closed** 2024-02-06 11:36 UTC
Labels: Bug, QA Passed, Bug Fixed
