### ISSUE TITLE
Issue in Image slider in theme 

### ISSUE THREAD

**Issue by 23gauravS** [bagisto/bagisto#9443] opened 2024-02-12 13:35 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

Hello, I wanted to add and change new images to the slider section as described in the document you sent. (2.png and 3.png). However, it did not display the images I added, and the default slider that came with it copied itself like the one in bottom ( 1.png)
![6](https://github.com/bagisto/bagisto/assets/156195308/1078124d-8946-45ff-b775-d80d884d1ace)
![5](https://github.com/bagisto/bagisto/assets/156195308/1694aa2a-f22c-41d8-9268-07b442f46426)
![4](https://github.com/bagisto/bagisto/assets/156195308/0f904eb0-0178-415e-a3f4-e2531462aa7f)
![3](https://github.com/bagisto/bagisto/assets/156195308/e73ccb23-3f33-4d7a-93c5-32c02354ec95)
![2](https://github.com/bagisto/bagisto/assets/156195308/98150ba3-ede2-4595-8f7f-03ae79363bc3)
![1](https://github.com/bagisto/bagisto/assets/156195308/5a9dc328-0d15-4781-96e9-925242d674b1)
Issue

### Preconditions

As mentioned in the Issue Description.

### Steps to reproduce

Described in Issue Description

### Expected Result

The client needs to preview the custom theme they made.

### Actual Result

Facing double slider issue while creating a new one.

**Comment by shivendra-webkul** [comment] 2024-02-12 13:51
Hi @23gauravS,

Thank you for your attention to this matter. I wanted to inform you that the reported issue has already been addressed and fixed in the master branch of our codebase.

Please proceed to update your local codebase to ensure that you are working with the latest changes and that the issue is resolved on your end as well.

If you have any further questions or encounter any other issues, feel free to reach out. Your cooperation is much appreciated.

**Closed** 2024-02-14 08:00 UTC
Labels: Not An Issue
