### ISSUE TITLE
Specific coupon applied full discount instead of fixed amount

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3923] opened 2020-09-10 01:14 UTC
# Bug report

### Title
Specific coupon applied full discount instead of fixed amount

### Issue Description
Specific coupon applied full discount instead of fixed amount

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. latest master pull

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. create a promotion with a specific coupon name
    2. add action only.. fixed amount on the whole cart = $50, free_shipping = yes
    3. try to apply this coupon...

### Expected result
Only get $50 discount

### Actual result
Only get the full discount(all item free)

**Comment by bhanu-webkul** [comment] 2020-09-10 04:29
@otheriz 
first thing we have disabled free shipping field for action type fixed amount to whole cart - https://prnt.sc/uenwgc
so mentioned steps to reproduce cant be possible

**Comment by otheriz** [comment] 2020-09-10 05:25
@bhanu-webkul , 
but if we set the free shipping field to "yes" it still gets the free shipping..why disabled it btw?

this is my setting https://prnt.sc/ueoiif
this is the result http://prnt.sc/ueojy7


My CartRule.php already the same like 
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/CartRule/src/Helpers/CartRule.php

**Comment by bhanu-webkul** [comment] 2020-09-10 05:54
free shipping field is disabled because, fixed amount to whole cart gets applied over grand total which includes everything. 
As per your setting you have given discount 200, is it in USD or in which currency, if not USD could you please attach screenshot of exchange rate.

**Comment by otheriz** [comment] 2020-09-10 06:11
It's AED(United Arab Emirates dirham)..i don't have any exchange rate..
![image](https://user-images.githubusercontent.com/11325840/92688028-ca08a780-f366-11ea-9d1e-ad3c1c68baed.png)

My currency only AED
![image](https://user-images.githubusercontent.com/11325840/92688086-e7d60c80-f366-11ea-8492-ec002d253dc6.png)

My .Env and config Currency already AED too..
![image](https://user-images.githubusercontent.com/11325840/92688148-0d631600-f367-11ea-8e08-22fc21477c5b.png)

**Comment by bhanu-webkul** [comment] 2020-09-11 05:22
@otheriz 

I have checked in master , its working fine
this is my setting - https://prnt.sc/ufbmuy
this is the result- https://prnt.sc/ufbq1b

**Comment by otheriz** [comment] 2020-09-11 13:03
@bhanu-webkul ,
The condition is all null right ??

can you tell me what is the files that affect this coupon think ?

**Comment by bhanu-webkul** [comment] 2020-09-11 13:09
working in both case, with and without condition

**Comment by otheriz** [comment] 2020-09-12 10:00
I get the problem but not knowing yet how to fix it..
Do you tried it with multiple items ?

somehow this lines
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/CartRule/src/Helpers/CartRule.php#L277

is triggered as much as the items of the cart..
that's why if i put 200, and on cart have 5 items...it will be multiplied to 200x5 = 1000 discount

**Comment by vaishaliwebkul** [comment] 2021-02-01 09:12
@otheriz 
duplicate cart rule issue has been fixed as mention here https://github.com/bagisto/bagisto/issues/4392
So closing this right now, feel free to reopen if you're still having the same issue.

**Closed by vaishaliwebkul** 2021-02-01 09:12 UTC
Labels: Question
