### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by parimahziyi** [bagisto/bagisto#1159] opened 2019-07-07 10:12 UTC
Hi 
I wanna install  your project  but this error: "whoops, looks like something went wrong" happen in the installation process
or I have been installed your project and copy in another sys again this error happened
could you help me?

**Comment by rahulshukla-webkul** [comment] 2019-07-08 06:23
Hi @parimahziyi 

Can you tell me, when & where you got this error & please attach a screenshot for the same so that it will easy for us to resolve this ASAP.

**Comment by parimahziyi** [comment] 2019-07-08 09:32
I follow all of the steps you mention in installation. migration and seed have done completely but when I wanna run the project, mean "php artisan serve" and go to 127.0.0.1:8000 this error happened. and I should say for the bad quality of the picture. that was unavailable for me now.

![Capture554t6](https://user-images.githubusercontent.com/37453809/60799646-c7ba2480-a188-11e9-9c50-3a73e7a8cf1d.PNG)

**Comment by rahulshukla-webkul** [comment] 2019-07-08 10:26
Hi @parimahziyi 

Can you send me your error log file.

**Comment by parimahziyi** [comment] 2019-07-08 19:37
[laravel.log](https://github.com/bagisto/bagisto/files/3369955/laravel.log)
 here you are.it says there is no key for project ya?
I use this command: php artisan key:generate

**Comment by parimahziyi** [comment] 2019-07-08 19:38
but nothing happened so

**Comment by rahulshukla-webkul** [comment] 2019-07-09 04:13
Hi,

Please run the following commands - 
1. composer dump-autload
2. php artisan vendor:publish
-> Press 0 and then press enter to publish all assets and configurations.

**Comment by sadafm** [comment] 2019-07-09 09:47
i am trying to install on localhost and live server but i a facing error when run mirgration and seed command please check iamge and guide me 
![image](https://user-images.githubusercontent.com/3682289/60878033-66618680-a258-11e9-8e8d-098814a803f7.png)

**Comment by rahulshukla-webkul** [comment] 2019-07-09 10:06
Hi @parimahziyi 

Please upgrade your database version which supports json columns because we are using JSON column and your current MariaDB  version does not support it.

follow this link for solution - https://stackoverflow.com/questions/44027926/update-xampp-from-maria-db-10-1-to-10-2

Thanks

**Comment by rahulshukla-webkul** [comment] 2019-07-09 10:07
duplicate of #552, #421.

**Comment by sadafm** [comment] 2019-07-09 10:45
which version we need ?

**Comment by rahulshukla-webkul** [comment] 2019-07-09 11:18
10.2

**Comment by parimahziyi** [comment] 2019-07-09 11:35
thanks a lot. it worked for me!

**Comment by rahulshukla-webkul** [comment] 2019-07-09 11:46
Issue is resolved !!!

**Closed by rahulshukla-webkul** 2019-07-09 11:46 UTC
