### ISSUE TITLE
Magic AI Configuration is disable, still we are able to see the Magic AI details in Products Descriptions and UI is not appropriate.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9086] opened 2023-12-05 06:35 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we check the magic AI options, there we have disabled the Feature and when we check the admin end Products description,  , there we can see that the Magic AI option is still appearing and also the UI is not appropriate.

### Preconditions

1. Admin Should be Logged In.

### Steps to reproduce

1. Go to Admin -> Configure -> General -> Magic AI -> Status -> Disable -> Save.
2. Go to Catalog -> Products -> Create/Edit any product -> Check the Magic AI option.
3. It should not appear if the feature is disabled.

### Expected Result

It should be disable when the feature is  not active and also if enabled UI should be accurate.

### Actual Result

Currently we can see that the UI is not apparopriate and also the It should be disabled when not in use.

### Screenshots

Admin End  - https://prnt.sc/fapLo45UVK0P
Product Page - https://prnt.sc/yvrf6G8Dvjw1

**Comment by jitendra-webkul** [comment] 2023-12-05 06:38
Duplicate of #9077

**Closed by jitendra-webkul** 2023-12-05 06:38 UTC
Labels: Bug, UI
