### ISSUE TITLE
Displaying incorrect number of product on front-end.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#533] opened 2019-02-02 09:55 UTC
Framework Version: 0.1.4
![screenshot 84](https://user-images.githubusercontent.com/45203177/52162764-b4e58480-26fe-11e9-87e4-46f6c1e8374f.png)

**Comment by jitendra-webkul** [comment] 2019-02-04 07:21
duplicate of #532

**Closed by jitendra-webkul** 2019-02-04 07:21 UTC
Labels: bug, shop
