### ISSUE TITLE
alligment should be done properly  in arabic in wishlist page 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5789] opened 2022-02-11 08:26 UTC
## Bagisto Version

1. go to compare page 

## Steps To Reproduce

1.   go  to compare page 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/153559051-c72887ba-f024-4c52-861b-4969bf018d0b.png)

**Comment by Sanjaybhattwebkul** [comment] 2022-02-24 10:32
@devansh-webkul  @singhgagan03 
I am not able to reproduce this issue. There is no UI issue in the Arabic locale. Please find the screenshot [Here](https://prnt.sc/8ZQ8okmZj6Nt).

@prateek-webkul  can you please verify this.

**Comment by Sanjaybhattwebkul** [comment] 2022-02-24 12:21
@prateek-webkul 
Now, this **issue is fixed**. so I am **closing** this issue
And I have attached a screenshot for future reference [Here](https://prnt.sc/LP0f33BKnJnj).

**Closed by Sanjaybhattwebkul** 2022-02-24 12:21 UTC
Labels: Bug, Bug Fixed
