### ISSUE TITLE
Memory allocation because of contineously page refresh hitting request

### ISSUE THREAD

**Issue by faizy7sheikh** [bagisto/bagisto#8615] opened 2023-10-06 05:41 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.5.1

### Issue Description

when I open website on chrome. it will load the content but the top leading is continuously running . when i checked network tab then it's continue hitting the request because of that memory got allocated . when i open other menu or tab then i am getting `Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2568 bytes)` like that error. I have memory_limit = 4096M in php.ini file but still getting same error.check the link for reference.[https://play.streamingvideoprovider.com/popplayer.php?it=91zlthqttg08&is_link=1&w=720&h=405&pause=1&title=04.10.2023_16.45.32_REC&skin=3&repeat=&brandNW=1&start_volume=34&bg_gradient1=%23ffffff&bg_gradient2=%23e9e9e9&fullscreen=1&fs_mode=2&skinAlpha=50&colorBase=%23250864&colorIcon=%23ffffff&colorHighlight=%237f54f8&direct=false&no_ctrl=&auto_hide=1&viewers_limit=0&cc_position=bottom&cc_positionOffset=70&cc_multiplier=0.03&cc_textColor=%23ffffff&cc_textOutlineColor=%23ffffff&cc_bkgColor=%23000000&cc_bkgAlpha=0.1&image=https%3A%2F%2Fmember.streamingvideoprovider.com%2Fpanel%2Fserver%2Fclip%3Fa%3DGenerateThumbnail%26clip_id%3D7329183%26size%3Dlarge&mainBg_Color=%23ffffff&aspect_ratio=16%3A9&play_button=1&play_button_style=pulsing&sleek_player=1&stretch=&auto_play=0&auto_play_type=unMute&floating_player=none](url)

### Preconditions

setup the project in local
open project in chrome 
inspect the memory issue

### Steps to reproduce

1. Go to 'home page'
2. open network tab 
3. check the request hitting or we can also check memory usage increasing

### Expected Result

website most have good seo and performance.if we check in chrome lighthouse we are getting bad result

### Actual Result

we want to destroy the object to release the memory

**Comment by devansh-webkul** [comment] 2023-10-09 08:16
Not able to reproduce that checked both 1.5.1 and master version in chrome and mozilla both.

**Comment by devansh-webkul** [comment] 2023-10-09 08:21
Please provide valid steps to reproduce to open this issue. I am closing as of now.

**Closed by devansh-webkul** 2023-10-09 08:21 UTC
