### ISSUE TITLE
Unable to update visible in menu option for a category.

### ISSUE THREAD

**Issue by phyothiha** [bagisto/bagisto#8972] opened 2023-11-09 15:49 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

Cannot update category's visible in menu option to hide from menu.

### Preconditions

1. Logged in as admin
2. Create a new category
3. Edit the category and toggled off "visible in menu" option

### Steps to reproduce

1. Log into 'Admin Panel'
2. Click on 'Catalog' menu and then click 'Categories'
3. Click 'Create Category' button if there is none or select an existing category to edit
4. Toggle off 'Visible in Menu' option and then click 'Save Category'

### Expected Result

Visible in Menu toggle button should be inactive after saving.

### Actual Result

The toggle remains active.

1. https://prnt.sc/iEUg9k-OBUzo
2. https://prnt.sc/a_ZmZvwBr7Fa

**Comment by shivendra-webkul** [comment] 2023-11-10 04:20
@phyothiha thank you for informing us. This issue is already fixed in https://github.com/bagisto/bagisto/pull/8859/files this PR now it is working fine. Please take the latest pull.
https://github.com/bagisto/bagisto/assets/121868701/318ba2bb-4d02-4d92-9a06-c155e7105bfa

**Comment by Amitk-webkul** [comment] 2023-11-10 08:17
@phyothiha Please take the latest pull request. the issue is already fixed. so closing this issue.

**Closed by Amitk-webkul** 2023-11-10 08:17 UTC
Labels: Not An Issue
