### ISSUE TITLE
pending payment error when i create transaction

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#5086] opened 2021-08-17 09:01 UTC
### Issue Description
I create an order with automatic invoice and payment at the door and add a payment from the transactions page, but the status remains as pending payment and does not change.

I got the error in the video, you can check it
https://drive.google.com/file/d/1b8vYqLHFJDQmCyIAZy6kaxoLAkVKCU7M/view?usp=sharing

### Preconditions
- I create an order as a customer, I choose the payment method, payment at the door
- I add process in admin panel
- invoice status pending payment

#### Bagisto version
- [ ] master branch
- [ [] ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

local.ERROR: Call to undefined method Webkul\Product\Type\Configurable::evaluatePrice() (View: /home/ardenoff/public_html/resources/themes/velocity/views/products/price.blade.php) {"view":{"view":"/home/ardenoff/public_html/packages/Webkul/Product/src/Type/Configurable.php","data":[]},"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Call to undefined method Webkul\\Product\\Type\\Configurable::evaluatePrice() (View: /home/ardenoff/public_html/resources/themes/velocity/views/products/price.blade.php) at /home/ardenoff/public_html/packages/Webkul/Product/src/Type/Configurable.php:580)
[stacktrace]

![image](https://user-images.githubusercontent.com/65822345/129695335-ab5c15c4-72c5-40fa-82c0-06e8b70cd93f.png)

**Comment by devansh-webkul** [comment] 2021-08-17 09:14
Hi @Arsivpro,

I just checked in the fresh instance and it is not reproducible. Do you upgrade the project or using the fresh instance.

**Comment by Arsivpro** [comment] 2021-08-17 09:19
@devansh-webkul I am using the project you see. I complete the code update with the incoming commit update

**Comment by devansh-webkul** [comment] 2021-08-17 09:23
@Arsivpro,

The error `evaluatePrice()` undefined which you are saying, its already present and i am not able to reproduce this,
https://github.com/bagisto/bagisto/blob/7cd34d0a03ef7b4d0794fcec179971f1ae508075/packages/Webkul/Product/src/Type/AbstractType.php#L802

**Comment by Arsivpro** [comment] 2021-08-17 09:24
@devansh-webkul Are you saying it's a bug that's being worked on?

**Comment by devansh-webkul** [comment] 2021-08-17 09:25
No, I am saying it's not reproduced what you are saying. It looks like you have upgraded your version.

**Comment by Arsivpro** [comment] 2021-08-17 09:27
@devansh-webkul this is correct i upgraded i am on latest version

**Comment by devansh-webkul** [comment] 2021-08-17 09:30
Yes, check whether all changes are present or not. Maybe some small issue is there.

**Comment by Arsivpro** [comment] 2021-08-17 09:36
After updating this page, there were a few problems, I think the problem is here,
1st error tax 18%, price 1.6949 should appear price 2, 1.99 rounding error seen
The second error is that it shows the pending payment when the transaction is added to the invoice.
https://github.com/bagisto/bagisto/blob/7cd34d0a03ef7b4d0794fcec179971f1ae508075/packages/Webkul/Product/src/Type/AbstractType.php

**Comment by devansh-webkul** [comment] 2021-08-17 09:38
In the latest version, we have implemented several features like tax enhancement. I can best suggest you take a replica of the fresh latest version also. If a bug is found in the latest version then let us know.

**Comment by Arsivpro** [comment] 2021-08-17 09:42
@devansh-webkul  I did the tax updates without any errors, even I thought there would be a problem and ran it by installing a different bagisto project, but there is a problem with rounding.
Example I entered the product with 18% tax, the price is 1.6949, on the front end it should appear: 2, visible: 1.99

**Comment by devansh-webkul** [comment] 2021-08-17 09:48
Hi, can you just verify here also,
https://bagisto-speed.webkul.com/

**Comment by Arsivpro** [comment] 2021-08-17 09:54
@devansh-webkul You can view this product, tax 18% price 1.6949 should appear $2, display $1.99
https://bagisto-speed.webkul.com/sunglasses

**Comment by devansh-webkul** [comment] 2021-08-17 09:59
The product price is $1.69.

The 18% of $1.69 is  $0.30.

Total: $1.69 + $0.30 = $1.99

And the default it is rounded to 2 decimal place so it can't be $2.

**Comment by Arsivpro** [comment] 2021-08-17 10:06
@devansh-webkul open the calculator and do 2/1.18 and see the result, each of my products is moving in this direction, I write the fraction as 5 numbers, actually 18% of 2 is 0.36

**Comment by Arsivpro** [comment] 2021-08-17 10:08
@devansh-webkul but instead of doing 2*18 % + = in tax calculations, I do 2/0.18 because the result is rounded

**Comment by devansh-webkul** [comment] 2021-08-17 10:16
Results are rounded off to two. The calculations are showing right as per the calculations I can't do anything on this.

**Comment by Arsivpro** [comment] 2021-08-17 10:20
@devansh-webkul Your opinion is important to me. Any suggestions on how to write 2$ with 18% tax calculated?

**Comment by devansh-webkul** [comment] 2021-08-17 10:30
I understand your concern I will update you regarding the same.

**Comment by Arsivpro** [comment] 2021-08-17 10:32
@devansh-webkul ok i'm waiting on the issue

**Comment by devansh-webkul** [comment] 2021-08-17 11:41
Well, I just tested everything rounded off reverse can't be possible because of 18 per cent tax and the round of 2 and this is default behaviour either you need to customize something to meet your need.

Even in the calculator, it's going $1.999995. So logically  $1.99 is right.

**Comment by Arsivpro** [comment] 2021-08-17 11:56
@devansh-webkul  Bagisto system does not use 2*18%-= when calculating tax, instead it uses 2/1.18 system, so it is a bit unlikely that my calculation is wrong because it only happens on some products, 6 products out of 200 have this error

**Comment by devansh-webkul** [comment] 2021-08-17 12:08
Alright, I am closing this as I haven't seen anything. For you, you can customize it, if you want. For discussion, you can use the Bagisto forum.

**Closed by devansh-webkul** 2021-08-17 12:08 UTC
Labels: Help Wanted
