### ISSUE TITLE
After uploading on server rupees symbol not showing

### ISSUE THREAD

**Issue by digiapps** [bagisto/bagisto#2980] opened 2020-04-30 15:16 UTC
After uploading on server rupees symbol not showing on front end while in admin its showing. On local host its showing at both end. On live server its showing Rs. Instead of symbol. Please see screenshots-

Live Server 
![image](https://user-images.githubusercontent.com/8210369/80727611-8cc41b80-8b23-11ea-9d53-ca0b7c9d734a.png)
Local Server 
![image](https://user-images.githubusercontent.com/8210369/80727670-9fd6eb80-8b23-11ea-9442-71a2dea4fde8.png)

**Comment by rahulcs0082** [comment] 2020-05-04 05:00
HI @digiapps

Can you tell me about your server environment?

**Comment by digiapps** [comment] 2020-05-04 05:18
Hi Rahul,

Its fixed by your team. 

Thank You

**Comment by vaishaliwebkul** [comment] 2020-05-13 05:19
I hope the issue is resolved, so We are closing this.
Feel free to reopen this issue.

**Closed by vaishaliwebkul** 2020-05-13 05:19 UTC
Labels: help wanted
