### ISSUE TITLE
there should be an option so that user can change the quanity of product when they view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5690] opened 2022-01-25 08:27 UTC
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1.select any product 

## Actual Result
![1](https://user-images.githubusercontent.com/96044834/150939477-d962ca95-96b7-4e40-a1aa-9378649fec34.png)

## Expected Result
![2](https://user-images.githubusercontent.com/96044834/150939743-0b918c62-a524-4518-82ad-2c917cfcce56.png)

**Comment by jitendra-webkul** [comment] 2022-03-31 08:27
Duplicate of #5595

**Closed by jitendra-webkul** 2022-03-31 08:27 UTC
Labels: Feature Request
