### ISSUE TITLE
Paypal smart button not working. It's giving Order Id issue.

### ISSUE THREAD

**Issue by engineer-ashwattha** [bagisto/bagisto#7514] opened 2023-04-18 09:10 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

I tried paypal with both Sandbox as well as Live version for PayPal smart button feature of Bagisto.

When we click on PayPal button on Checkout page, the alrt box popups saying "something went wrong" and when we debug, it shows the issue with the order id.

Check this screenshot: https://prnt.sc/Z7f1_199K2VT.

And yes, I am 100% sure about the correct client ID and secret key. I have also setup the same currency as per my PayPal account.

Also, "Paypal Standard" not working. It takes the user to the PayPal page but then shows the error.

### Preconditions

I am using Bagisto version of "v1.4.5".  I am not testing the checkout on Local. It's on one of our beta urls here: https://demo.arkabotanicals.com/

### Steps to reproduce

1. Enable Paypal standard in admin panel
2. Enable paypal smart button in admin panel
3. add items into the cart
4. fill up the ckout form and test both paypal buttons

### Expected Result

It should allow user to place an order with PayPal.

### Actual Result

PayPal is giving error.

### Screenshots

 https://prnt.sc/Z7f1_199K2VT

**Comment by devansh-webkul** [comment] 2023-04-19 08:27
Please check your instance and cedentials, as this is not able to reproduce.

**Comment by engineer-ashwattha** [comment] 2023-04-20 05:58
Credentials and setup are double checked. They are of sandbox mode. I even tested it one more time and it is giving me the same error as mentioned. Check the screenshot of latest testing here: https://prnt.sc/_92BM3ZI3Quf

**Comment by jitendra-webkul** [comment] 2023-04-20 06:03
Please share the logs so that we can have a better understanding of the issue.

**Comment by engineer-ashwattha** [comment] 2023-04-20 06:27
[laravel.log](https://github.com/bagisto/bagisto/files/11280497/laravel.log)

Check uploaded log file.

**Comment by devansh-webkul** [comment] 2023-04-21 05:48
From the log i am not able to see anything its look like your classes are not autoloaded yet. Also please check the response, comming from the paypal.

**Comment by engineer-ashwattha** [comment] 2023-04-24 02:35
The debug is already ON. So, if it's not logging the paypal bug, it means there's another kind of bug. We haven't changed any of the core files.

It is not going even to the PayPal - how would I check the response? Even before going to paypal: the log gives me this error: https://prnt.sc/Z7f1_199K2VT

**Comment by engineer-ashwattha** [comment] 2023-04-27 09:55
Hello!

Is there any update on this?

**Comment by devansh-webkul** [comment] 2023-05-01 09:00
I just checked your website and this is the response coming from PayPal,
![Screenshot from 2023-05-01 14-29-09](https://user-images.githubusercontent.com/68321766/235432154-6c02e127-122a-47ba-9d77-6f149ee66b2b.png)


Check your currency and sandbox mode.

**Comment by engineer-ashwattha** [comment] 2023-05-02 10:25
I have set the acceptance currency as USD and in my paypal account too it's set as USD. Then why this error is coming?
![Screenshot from 2023-05-02 15-54-34](https://user-images.githubusercontent.com/98952898/235642463-ca9b7196-d4ca-40a2-b5fe-ead6f8891765.png)

**Comment by mabehiry** [comment] 2024-02-09 18:21
I am getting the same error. How did you solve it please?

**Comment by ashishkumar-webkul** [comment] 2024-02-14 11:56
@mabehiry 

Thank You so much for your concern as I have checked the PayPal Smart Button functionality with the latest master branch and there it is working fine. Please check the video for the referece and screenshot. In case you find any issue please help us with the steps and screenshots so that we could understand your query.

We really appreciate your contribution.

For now I am closing the issue. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/d9aba23a-1929-45fb-845c-3a67cb57d92e

![Screenshot from 2024-02-14 17-17-55](https://github.com/bagisto/bagisto/assets/92721837/7d0f877a-0ad7-4999-9c6d-6a3bcb873214)

**Closed by ashishkumar-webkul** 2024-02-14 11:56 UTC
