### ISSUE TITLE
User should be able to add product images while writing a review of a product. This functionality is present in Amazon, FK and other E-Comm. platforms

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4650] opened 2021-02-17 12:12 UTC
https://prnt.sc/zumojd

**Comment by rahulshukla-webkul** [comment] 2021-04-07 12:59
Duplicate of - https://github.com/bagisto/bagisto/issues/4754

**Closed by rahulshukla-webkul** 2021-04-07 12:59 UTC
Labels: Enhancement
