### ISSUE TITLE
Google Recaptcha not working and looping : Uncaught (in promise) Timeout

### ISSUE THREAD

**Issue by Arachnos** [bagisto/bagisto#5388] opened 2021-12-05 12:01 UTC
# Bug Report

## Issue Description
Google Recaptcha v2 is not working and I get an error "Uncaught (in promise) Timeout"

## Bagisto Version
- [ x ] 1.3.3
- [ x ] 1.3.2

## Steps To Reproduce
It is the same error when we try on demo site https://demo.bagisto.com/

## Actual Result
We are unable to make the captcha functionnal, but when we de-activate `velocity.js` or `velocity-core.js` the captcha is working as expected.

It seems that there is an error in `app.js` or Vue components but we are unable to find what is making the error.

**Comment by devansh-webkul** [comment] 2021-12-06 04:27
I just tried with my own site ket and credentials in Bagisto demo and it's working fine. Have a look,

![Screenshot from 2021-12-06 09-56-00](https://user-images.githubusercontent.com/68321766/144787157-d9652f41-a795-46c5-aed8-346866c8aba8.png)

**Comment by devansh-webkul** [comment] 2021-12-06 04:37
Sometimes it usually happens when you are using captcha frequently.

I am closing this issue, for any help please use Bagisto forum,
https://forums.bagisto.com/

**Closed by devansh-webkul** 2021-12-06 04:37 UTC
Labels: Help Wanted

**Comment by Arachnos** [comment] 2021-12-06 08:55
The error is almost systematic.

I have solved the issue by addding this code below line 91 of `app-core.js` :
```
loadDynamicScript(`${baseUrl}/${retrothemeJSPath}`, () => {});
loadDynamicScript('https://www.google.com/recaptcha/api.js', () => {});
```

This loads the reCaptcha script after `velocity.js` is loaded.

**Comment by saad3074** [comment] 2022-06-27 09:59
I am facing the same issue. after clearing cache it works fine but on next refresh it showing error in console and loading in loop. `anchor:1 Uncaught (in promise) Timeout (f)`

**Comment by saad3074** [comment] 2022-06-27 09:59
I am facing the same issue. after clearing cache it works fine but on next refresh it showing error in console and loading in loop. `anchor:1 Uncaught (in promise) Timeout (f)`

**Comment by akies1** [comment] 2023-05-16 07:59
Yes ,this issue is still there.

**Comment by ghermans** [comment] 2025-03-19 11:33
> Even now in version 2.2.3...

@devansh-webkul can you confirm this?

**Comment by devansh-webkul** [comment] 2025-03-19 12:08
@ghermans,

This issue was relevant for the 1.x version, where it was working fine. However, it was later reported for the 2.x version,
https://github.com/bagisto/bagisto/issues/10497

which is already fixed,
https://github.com/bagisto/bagisto/pull/10503

**Comment by EsterDahri1** [comment] 2025-03-27 10:48
https://github.com/user-attachments/assets/35c2da34-2438-43da-b18a-af9257126e62

Dear all,

Apologies for the delayed response. I’m attaching a screen recording to illustrate the issue I am encountering.

For reference, I have followed the documentation outlined here to activate it: [reCAPTCHA in Bagisto](https://bagisto.com/en/how-to-use-google-recaptcha-in-bagisto/)

Please let me know your thoughts. Thank you for your support.

Best regards

**Comment by devansh-webkul** [comment] 2025-03-27 10:54
Hello @EsterDahri1,

I have one query, can you verify these changes in your code,
https://github.com/bagisto/bagisto/pull/10503/files

Because we were able to reproduce this issue and have already fixed it. If you're still facing it, I will reverify. Thank you for reporting this.

**Comment by EsterDahri1** [comment] 2025-03-27 11:11
Hi @devansh-webkul,

just made the changes 👍 everything regarding reCAPTCHA works fine now. Thank you 😊

**Comment by devansh-webkul** [comment] 2025-03-27 11:56
Thanks for the update. 😃 

Also, if you like our support, you may give us the review here: https://www.trustpilot.com/review/bagisto.com

That would be grateful for us. 🚀
