### ISSUE TITLE
While a product has deleted, and the order view and order refund have error report and can't do it continue

### ISSUE THREAD

**Issue by xxl4** [bagisto/bagisto#9645] opened 2024-04-12 02:50 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0

### Issue Description

While a product has deleted, and the order view and order refund have error report and can't do it continue.

Today, When i found our a product have error info, and then i delete it,  and this product has many orders include it, 

when i view this product's order or refund and has error report.

### Preconditions

While a product has deleted, and the order view and order refund have error report and can't do it continue.

Today, When i found our a product have error info, and then i delete it,  and this product has many orders include it, 

when i view this product's order or refund and has error report.

### Steps to reproduce

While a product has deleted, and the order view and order refund have error report and can't do it continue.

Today, When i found our a product have error info, and then i delete it,  and this product has many orders include it, 

when i view this product's order or refund and has error report.

### Expected Result

While a product has deleted, and the order view and order refund have error report and can't do it continue.

Today, When i found our a product have error info, and then i delete it,  and this product has many orders include it, 

when i view this product's order or refund and has error report.

### Actual Result

While a product has deleted, and the order view and order refund have error report and can't do it continue.

Today, When i found our a product have error info, and then i delete it,  and this product has many orders include it, 

when i view this product's order or refund and has error report.

**Comment by ashishkumar-webkul** [comment] 2024-04-12 06:03
@xxl4 

Thank you so much for reporting the issue and for your contribution to Bagisto. We truly appreciate your efforts. Upon checking, I found that the issue is indeed occurring. We will address this promptly and update you as soon as possible.

Please find the screenshot below.

![Screenshot from 2024-04-12 11-29-25](https://github.com/bagisto/bagisto/assets/92721837/e60e9e04-c8ec-4b76-8160-6eb404cfe771)

**Comment by ashishkumar-webkul** [comment] 2024-04-12 08:55
Checked and found that the issue has been fixed and PR has been merged, in case you find any issue we would love to help you in same. Hence I am closing the issue. For reference you can check the video.

Thank You, 

**Video**


https://github.com/bagisto/bagisto/assets/92721837/e9e24610-4858-45e2-9535-cf1eecd80e7b

**Closed by ashishkumar-webkul** 2024-04-12 08:55 UTC
Labels: Bug, Bug Fixed, Fix Proposed

**Comment by xxl4** [comment] 2024-04-14 02:42
Thank you!
