### ISSUE TITLE
Selecting All Channels from admin product list throws error

### ISSUE THREAD

**Issue by stevechai** [bagisto/bagisto#4755] opened 2021-03-23 06:15 UTC
# Bug report

### Title
Selecting All Channels from admin product list throws error

### Issue Description
Console showing "TypeError: Cannot read property 'name' of undefined" when select All Channels from admin product list channel dropdown

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch
    2. 3159762

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. fresh install
    2. goto /admin/catalog/products?channel=all

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by devansh-webkul** [comment] 2021-03-23 08:46
On checking this, the issue able to reproduce some console errors but it won't impact the results. I am marking this as a bug because the console should be clean.

**Closed** 2021-03-24 23:59 UTC
Labels: Bug, Bug Fixed
