### ISSUE TITLE
Getting an exception while using duplicate SKU in the variant product.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8288] opened 2023-09-12 10:51 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While deleting the variant add another variant use the deleted variant product SKU in the new variant product and save it here it is showing an exception.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one configurable product.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'edit product' inside the catalog/products
3. Scroll down to 'variant products'
4. Delete a variant
5. Add a new variant and enter the deleted SKU in this variant 
6. Click on the save button
7. See error

### Expected Result

It should not be shown as an exception.

### Actual Result

But getting an exception while saving the details. [Here](https://jam.dev/c/2fd99547-dfc6-4ddb-8fe2-282589e15b8b)

**Comment by Amitk-webkul** [comment] 2023-09-13 13:52
@shivendra-webkul The issue is partially fixed. 

The duplicate SKU notification should not be shown on that variant SKU used in others. [Here](https://prnt.sc/A00SEHmYqVYl)

**Comment by TheAbhishekIN** [comment] 2023-10-06 04:23
Hey @Amitk-webkul , could you please assign this issue to me?

**Comment by Amitk-webkul** [comment] 2023-10-12 05:27
Hi @TheAbhishekIN, Any update regarding this Issue?

**Comment by Amitk-webkul** [comment] 2023-10-19 13:14
Hi @TheAbhishekIN, there are no updates from you regarding this issue, so I'm assigning this issue to @amit-webkul.

**Comment by Amitk-webkul** [comment] 2023-10-26 15:15
@amit-webkul Any update regarding this issue?

**Comment by ashishkumar-webkul** [comment] 2023-11-29 03:49
Checked and Found that the issue is still appearing, please fix the issue, for reference please check the video.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/ceb9ef0b-1bdf-422b-abdc-77cc7d536154

**Comment by ashishkumar-webkul** [comment] 2023-11-29 10:45
As per the discussion with Jitendra sir, this is an invalid issue, and hence I am closing the issue from here.

**Closed by ashishkumar-webkul** 2023-11-29 10:45 UTC
Labels: Critical, Hacktoberfest, 2.x
