### ISSUE TITLE
In the admin panel, getting source code while returning to previous page from customers.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8177] opened 2023-09-06 08:34 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

In the admin panel, on the dashboard while viewing the customer details from clicking customers on the customer with most sales. after that returning back with clicking the back button of the browser.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one customer.
3. Admin should have at least one order with that customer.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Customer name'
3. Click on the back button of the browser
4. See the error

### Expected Result

it should be shown previous page.

### Actual Result

It shows showing source code in the response.[Here](https://webkul.chatwhizz.com/share/view-recording/64f8386eed7413059a849b13)

**Comment by jitendra-webkul** [comment] 2023-09-07 08:47
Duplicate of #8076

**Closed by jitendra-webkul** 2023-09-07 08:47 UTC
Labels: Critical, Discussion, 2.x
