### ISSUE TITLE
Migration Path not Found - Installation

### ISSUE THREAD

**Issue by CodeCures** [bagisto/bagisto#3908] opened 2020-09-07 11:22 UTC
The installation is process was great until i tried to publish the packages
This is what happens when i run php artisan vendor:publish
![publish_error](https://user-images.githubusercontent.com/20299519/92336312-1fa73080-f097-11ea-80ae-85303c208f77.JPG)

Well, I thought it was a minor issue until i tried to login to admin dashboard and that's where i gave up

![admin_error](https://user-images.githubusercontent.com/20299519/92336409-166a9380-f098-11ea-95e5-062be2cd57d5.JPG)

**Comment by vaishaliwebkul** [comment] 2020-09-07 12:35
Duplicate of this https://github.com/bagisto/bagisto/issues/3807

**Closed** 2020-09-07 15:09 UTC
Labels: Bug, Duplicate
