### ISSUE TITLE
Images is not showing for CMS pages

### ISSUE THREAD

**Issue by SameerKhan301999** [bagisto/bagisto#5378] opened 2021-12-02 12:43 UTC
# Bug Report

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

![Screenshot from 2021-12-02 18-12-58](https://user-images.githubusercontent.com/95420838/144424228-13370012-c395-4e6d-9f56-13ae56a8cd6f.png)

## Expected Result

https://user-images.githubusercontent.com/95420838/144423977-3d3f8d64-25d4-4aa6-afa3-43a9770f1aa9.mp4

**Comment by devansh-webkul** [comment] 2021-12-03 04:28
Not able to reproduce that, please have a look, please check your APP_URL,

![Screenshot](https://user-images.githubusercontent.com/68321766/144545093-094d92ab-8b84-4a1e-bfd9-8034401d9a73.png)

![front](https://user-images.githubusercontent.com/68321766/144545302-3a0bdb3e-f703-40e8-ba59-2d254cf1c6da.png)

**Comment by devansh-webkul** [comment] 2021-12-03 06:38
I am closing this as this is not an issue. Please use bagisto forum for further discussion.

**Closed by devansh-webkul** 2021-12-03 06:38 UTC
Labels: Not An Issue
