### ISSUE TITLE
Category not saved for Configurable product

### ISSUE THREAD

**Issue by elitedigitaltech** [bagisto/bagisto#3841] opened 2020-08-27 11:34 UTC
# Bug report

I created a Configurable product using color and size but product not saving properly.

I assigned price for each variant but after saving product not showing on front end due to category not saved. and in product listing all variants showing price 0. also I saved product deleting some variants but when again edited product shown all variants again and without checked category and now price showing in textbox.

![image](https://user-images.githubusercontent.com/8210369/91437020-d41aa880-e886-11ea-8097-ee07e495f063.png)

I selected category men in above but after edit its showing blank checkbox

![image](https://user-images.githubusercontent.com/8210369/91437232-31aef500-e887-11ea-82a4-d43a28019f1d.png)

Same for Price and quantity

![image](https://user-images.githubusercontent.com/8210369/91437055-e1379780-e886-11ea-951f-b1d24d2ede66.png)

After saving all quantity and price showing zero

![image](https://user-images.githubusercontent.com/8210369/91437176-15ab5380-e887-11ea-8dde-43173f1991c9.png)

    1. framework Version : -  latest
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by elite-digital** [comment] 2020-08-27 12:23
Some time its working and some time its not working I again deleted blank Variants and saved this time its saved correctly for this product category also showing and product display active and there is no blank variants in listing too.


But for other product when I did same its not worked same issue blank price , quantity for variants and deleted all variants when edited but after save all variants present with blank values.

Please help me to solve issue

**Comment by vaishaliwebkul** [comment] 2020-08-27 14:13
@elite-digital 
Your issue looks like the similar one https://github.com/bagisto/bagisto/issues/3558, 
I checked with the master branch as well as in Beta release but not able to reproduce this issue.

kindly update your code with the master branch then check again.

**Comment by vaishaliwebkul** [comment] 2020-09-07 15:14
Not getting any activity from the last 11 days so closing this issue.

Feel free to reopen anytime,

**Closed by vaishaliwebkul** 2020-09-07 15:14 UTC
