### ISSUE TITLE
getting API  error after opening categories named category

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/bagisto#5200] opened 2021-10-06 13:16 UTC
## Issue Description
Getting the category in JSON format instead of normal category when we create a category with the name "categories".

## Bagisto Version
- [x] master branch

## Steps To Reproduce
1. Create a category named as "categories "  in admin with the main category as Root.
2. Go to frontend and open the category-list .
3. Click on the category named categories .

## Actual Result
Getting categories in JSON format.

![actual](https://user-images.githubusercontent.com/92033944/136209669-88071d56-6877-49e7-9987-039efb7f4585.png)

## Expected Result
Categories must be visible like other categories.

![expected](https://user-images.githubusercontent.com/92033944/136209571-ddefaee1-8fa9-4f78-b63c-b86cc8001dd0.png)

**Comment by AbdullahFaqeir** [comment] 2021-10-06 14:37
Done fixing this, waiting for my current PR to be merged to submit a new one.

**Comment by devansh-webkul** [comment] 2021-10-07 03:44
hi @abdulhamid-alattar,

What if I make the category name to `categories-list` and assign that category to root?

**Comment by devansh-webkul** [comment] 2021-10-07 09:32
Yup that's the reason but the problem is the endpoint already created. For changing the endpoint needs to check further because maybe several external or paid modules may use this.

We can add one more slug-like `category-list/{category-name}` but the problem is need to check the impact as i mentioned above.

**Comment by devansh-webkul** [comment] 2021-10-08 03:37
Yes, this can also be done and you need one extra case for `categories` name also.

Rest backend is already validating the duplicates.

**Comment by devansh-webkul** [comment] 2021-10-08 17:24
I sugest you to hit a full PR as per your idea.

Then, we will test and check.

Take your time as good things always takes time 😇

**Comment by AbdullahFaqeir** [comment] 2021-10-09 14:01
Hi @devansh-webkul!

Can you please check this.

**Closed** 2022-01-21 11:54 UTC
Labels: Bug, Bug Fixed
