### ISSUE TITLE
DB Error while migrating a Database

### ISSUE THREAD

**Issue by anuragyadav8949** [bagisto/bagisto#1099] opened 2019-06-22 12:33 UTC
"Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1")"

**The above is error while migrating the DB,due to this only 5 tables are created**

**Comment by prashant-webkul** [comment] 2019-06-22 12:40
@anuragyadav8949 Please upgrade your database version which supports json columns.

**Comment by jitendra-webkul** [comment] 2019-06-27 10:29
duplicate of #552, #421

**Closed by jitendra-webkul** 2019-06-27 10:29 UTC
