### ISSUE TITLE
Shrink the white space so the listing will be viewed properly.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8971] opened 2023-11-09 12:49 UTC
### Is your feature request related to a problem? Please describe.

Shrink the white space in the mini cart so the product listing will be viewed properly. On the small screen, it does not show properly listing if there is more than one product. [Here](https://prnt.sc/S4e1n0Vc_gkB)

### Describe the solution you'd like

The listing should be shown properly.

**Comment by ashishkumar-webkul** [comment] 2023-11-17 07:31
Checked and Found that the issue is working fine and PR has been merged, So i am closing the issue from here.

Issue resolved Screenshot [here](https://prnt.sc/hdzk0e9GMOfV)

**Closed by ashishkumar-webkul** 2023-11-17 07:31 UTC
Labels: Done, Improvements, 2.x
