### ISSUE TITLE
When proceeding to checkout, an 'Undefined variable' error is occurring.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9434] opened 2024-02-09 12:52 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After adding a product to the cart, an 'Undefined variable' error occurs when proceeding to checkout.

### Preconditions

Add a product to the cart and proceed to checkout.

### Steps to reproduce

1. Go to 'shop'
2. Click on 'add to cart' for the product.
3. Continue to checkout.
4. See error.

### Expected Result

After adding a product to the cart, the checkout process should be smooth.

### Actual Result

After adding a product to the cart, an 'Undefined variable' error occurs when proceeding to checkout.

### Screenshots

![Screenshot from 2024-02-09 18-21-53](https://github.com/bagisto/bagisto/assets/45708520/2607653e-6cf7-424e-9826-cae36e3304d2)

**Comment by shivendra-webkul** [comment] 2024-02-12 08:10
Hi @sunarcrajneesh Thank you for your attention, After thoroughly reviewing the codebase in our updated master branch, it appears that the variable mentioned in the issue is not present may be your master is not updated please update your branch with latest code. 
Not an issue:-https://webkul.chatwhizz.com/share/view-recording/65c9d24274648505848e888d

**Comment by ashishkumar-webkul** [comment] 2024-02-13 11:46
@sunarcrajneesh 

As I have checked and found that the checkout process is working fine in Master Branch. I am attaching a video for the reference,  please check the video. For now I am closing the issue. In case you are facing any such issue, please do let us know the exact case of the issue. 
We would really love to help you in your queries, really appreciated for your contribution.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/6f7d3f64-65f6-4cf8-adac-5959baef348a

**Closed by ashishkumar-webkul** 2024-02-13 11:46 UTC
Labels: Bug, Not An Issue
