### ISSUE TITLE
Invoice PDF breaking

### ISSUE THREAD

**Issue by fahadkhan1740** [bagisto/bagisto#4420] opened 2021-01-03 15:26 UTC
# Bug report

### Title
The Invoice PDF in Arabic is not able to render Arabic properly. 
The alphabets are getting isolated instead of staying connected.

### Issue Description
- English locale is correct here. Let me tell you what the problem is with an example since you might have a problem to understand Arabic, I'll explain with an example in Hindi.
- The word "Hindi" should be written as हिंदी. Instead of this, the characters are shown as हइनदई.
- Similarly, it is happening in Arabic. They should join the characters already but they don't.
- It is a very common issue in the Laravel Dompdf package.
   https://github.com/barryvdh/laravel-dompdf/issues/368
- If I can install Laravel Snappy and able to generate PDF, then that also might fix this issue.
I hope you understand the issue here.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Bagisto version - v1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create any product from this link https://zaahee.shop/.
    2. You may copy the title of product in Arabic.
    3. Place an order with the Arabic locale, and download the invoice.

### Expected result
**Tell us what should happen.**

- The product name should be like "عطر سيلفر سينت"

### Actual result

>    **Tell us what happens instead.**

- The product name is coming like attached.

[invoice-10-12-2020 (6).pdf](https://github.com/bagisto/bagisto/files/5761791/invoice-10-12-2020.6.pdf)

**Comment by ghermans** [comment] 2021-01-03 15:58
Hi @fahadkhan1740 thank you for reporting this issue, to help you out with this i would like to ask if you have tested this with the version from our master branch or from the release section?

**Comment by fahadkhan1740** [comment] 2021-01-03 18:59
Hi @ghermans, 

I downloaded this version from http://bagisto.com/en/download/ which was eventually `v1.2.0`

**Comment by ghermans** [comment] 2021-01-03 19:02
@fahadkhan1740 can you please verify if you also experience this issue with this one: https://github.com/bagisto/bagisto/archive/master.zip

**Comment by fahadkhan1740** [comment] 2021-01-03 19:20
@ghermans Yes, it has the same issue.

**Comment by vaishaliwebkul** [comment] 2021-01-12 09:06
getting exception while downloading Invoice PDF having composer version 2.0
![Screenshot_210](https://user-images.githubusercontent.com/43210406/104293019-87590680-54e3-11eb-88c4-31a9e66b1cf6.png)

**Comment by devansh-webkul** [comment] 2021-01-12 09:07
@vaishaliwebkul,

I will update you on the same.

**Comment by devansh-webkul** [comment] 2021-01-12 11:40
After upgrading to PHP 7.4 and composer 2.0, I am able to reproduce that bug. I Will hit PR once resolved.

**Comment by devansh-webkul** [comment] 2021-01-12 12:01
Hi @vaishaliwebkul and @ghermans,

The problem is coming from the package, so I made the PR,
https://github.com/khaled-alshamaa/ar-php/pull/3

Let see if this got merged then just need to update the version number.

**Comment by fahadkhan1740** [comment] 2021-01-16 07:36
> Hi @vaishaliwebkul and @ghermans,
> 
> The problem is coming from the package, so I made the PR,
> [khaled-alshamaa/ar-php#3](https://github.com/khaled-alshamaa/ar-php/pull/3)
> 
> Let see if this got merged then just need to update the version number.

I believe this has been merged. Can you please check?

**Comment by vaishaliwebkul** [comment] 2021-01-16 08:17
@fahadkhan1740 
the PR is approved https://github.com/khaled-alshamaa/ar-php/pull/3 but still waiting to be merge.

**Comment by fahadkhan1740** [comment] 2021-01-17 05:30
@vaishaliwebkul ok

**Closed** 2021-01-18 09:59 UTC
Labels: Bug

**Comment by khaled-alshamaa** [comment] 2021-01-26 00:53
Sorry to be late, it has been merged now, the new version 5.5.2 with the required fix has been released. Thanks for your support in resolve this issue.

**Comment by vishaldamasiya** [comment] 2022-02-22 04:54
my invoice pdf download error

Mpdf\MpdfException
Incorrect zoom display mode:

how to slove....??
