### ISSUE TITLE
Not able to save tax configuration

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8157] opened 2023-09-06 05:45 UTC
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Not able to save tax configuration

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'configuration section'
2. Scroll down to 'tax section
3. Click on catalog
4. Fill details and try to save
5. See an error

### Expected Result

Should be able to save the configuration

### Actual Result

Not able to save the configuration

### Screenshots

https://prnt.sc/rh1biDzdAUeK

**Comment by amit-webkul** [comment] 2023-09-06 11:12
Fixed

**Comment by Amitk-webkul** [comment] 2023-09-11 09:34
The issue is still there. [Here](https://prnt.sc/HtjV5puswu2z)

**Comment by Amitk-webkul** [comment] 2023-09-15 09:53
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/M8lfdOHDztwt), for future reference.

**Closed by Amitk-webkul** 2023-09-15 09:53 UTC
Labels: Bug, Bug Fixed, 2.x
