### ISSUE TITLE
API product detail return empty array

### ISSUE THREAD

**Issue by khanhgg** [bagisto/bagisto#2945] opened 2020-04-27 07:26 UTC
Hi,
I use API endpoint: /api/products/{id}, But it return empty array.
I am using Bagisto version 1.1.1

Please help me. Thanks

**Comment by autn** [comment] 2020-04-27 08:42
+1
I have same problem, the API works well at 1.1.0, but wrong when I upgraded to 1.1.1

**Comment by keeloren** [comment] 2020-04-27 08:53
Yes, I have the same problem. Can you help me, please?
The production release is very near :((

**Comment by vaishaliwebkul** [comment] 2020-05-13 05:40
@khanhgg 
 the issue is resolved. feel free to reopen this issue if it still exist.

**Comment by derMart** [comment] 2021-11-02 10:50
the issue is not resolved for me. I am using Bagisto 1.3.1
I do have active products showing up in the admin section, but the product api returns no items, please reopen.

**Comment by ghermans** [comment] 2021-11-02 15:51
Hi @derMart in the upcoming days we will investigate this issue.

**Comment by devansh-webkul** [comment] 2021-11-03 04:13
Hi @ghermans,

I am not able to reproduce this. Please provide steps to reproduce.

**Comment by derMart** [comment] 2021-11-03 20:57
@devansh-webkul I found the culprit. The problem was that the visible_individually attribute needs to be present in the attribute family. Products are not shown at all if that attribute is not existing, that was unexpected for me. Actually, it would be really nice to have some more documentation about the internal structure of bagisto in general and for this specific case, which attributes are really necessary (for which purpose) as they are hardcoded in the respective Repositories and which are not. This would be very helpful.

**Comment by devansh-webkul** [comment] 2021-11-08 04:47
Alright, in the future we will do it. Right now, I am closing this as this is not an issue.

**Closed by devansh-webkul** 2021-11-08 04:47 UTC
Labels: Investigating
