### ISSUE TITLE
Catalog Rules Active despite Set as Inactive and 'Does Not Contain' Conditions Reverting to 'Contains' in the Italian Admin Panel of Bagisto 2.0

### ISSUE THREAD

**Issue by matts93** [bagisto/bagisto#9329] opened 2024-01-16 10:34 UTC
**Describe the bug**
There are two problems in the Italian administrator panel of the latest fixed version of Bagisto. The first number is in the "Create Catalog Rules" section. When a rule is created and marked as inactive, it still remains active. It only becomes inactive if an earlier end date is set for the marketing event. The second problem is common to both 'Catalog Rules' and 'Cart Rules'. If the condition is set to "Categories" and "Does not contain" is selected, when saving and
modifying the rule again returns the condition to "Contains" instead of "Does not contain".

**Must play**
Go to "Marketing" > "Promotions" > "Catalog Rules" in your admin panel.
Click "Add Catalog Rule".
Create a rule and set it to inactive without setting an end date.
Save the rule and notice that it remains active in the front end.
Steps to reproduce the behavior for the second problem:

Go to "Marketing" > "Promotions" > "Catalog Rules" or "Cart Rules".
Click "Add Rule".
In the "Conditions" section, set the condition to "Categories" and "Does not contain".
Save the rule.
Edit the same rule and notice that the condition has changed back to "Contains".

**Expected behavior**
For the first issue, when a rule is marked as inactive, it should not be active unless an end date is specified. For the second issue, the conditions set for "Does not contain" should persist after saving and re-editing the rule, rather than reverting to "Contains".

**Additional context**
Add any other context about the issue here. The first issue indicates a possible flaw in the rule activation logic, while the second suggests a problem with the persistence of conditions in the rules management system.

Additional Information

Bagisto Version: 2.0 (Master with latest corrections)
Environment: Administrator Panel
Locale: Italian (it)

**Comment by ashishkumar-webkul** [comment] 2024-01-18 05:27
Checked and Found the the issue is appearing, please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/1668fb32-674e-4a7a-8020-65b51570cfc5

**Comment by ashishkumar-webkul** [comment] 2024-01-19 09:39
@shivendra-webkul 

As I have checked and Found that the issue has been fixed and working fine, please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/4eb7d9b7-a272-4fe2-8af0-35fbb0148cab

**Comment by ashishkumar-webkul** [comment] 2024-01-19 10:46
Checked and Found that the issue has been fixed and PR has been merged. Hence I am closing the issue.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/d904e1f0-0af0-4c71-9252-ec3432b8933f

**Closed by ashishkumar-webkul** 2024-01-19 10:46 UTC
Labels: Bug, QA Passed, Bug Fixed

**Comment by ashishkumar-webkul** [comment] 2024-01-22 05:27
@matts93 

Hello there, we will be fixing the other issue in [this](https://github.com/bagisto/bagisto/issues/9352) issue. 

Thanks for the update. We will be fixing this ASAP.
