### ISSUE TITLE
Cart (customer) address not persisted during the checkout

### ISSUE THREAD

**Issue by SpareShade** [bagisto/bagisto#2868] opened 2020-04-12 14:49 UTC
# Bug report

### Title
Cart (customer) address not persisted during the checkout

### Issue Description
During the checkout, customer's "selected" address should be persisted to the cart as "cart_address". This does not happen, see below sql query of the cart_address table right after the address has been assigned to the cart. Neither address1 nor addres2 are persisted
```
     vat_id: 
    address1: 
    address2: NULL
```

### Preconditions
**Please provide as detailed information about your environment as possible.**

### Steps to reproduce
The address1 gets overwritten during array merge at
```php
private Webkul\Checkout\Cart::gatherBillingAddress
```

As temp workaround, I've just changed the order of merging to this
```php
        $billingAddress = array_merge(
            $data['billing'],
            ['cart_id' => $cart->id],
            $this->fillCustomerAttributes(),
            $this->fillAddressAttributes($data['billing']),
            $customerAddress // moved it as last
        );
```

Issue #954 mentions that address2 is "persistable" during the checkout process, but according to the code above only address1 gets persisted...

**Comment by vaishaliwebkul** [comment] 2020-04-12 14:57
@SpareShade 
It has been resolved, here is the same issue link
https://github.com/bagisto/bagisto/issues/2785

**Comment by SpareShade** [comment] 2020-04-12 15:24
The address is appearing fine on the front-end, but if you post the details to Paypal, you will notice that both address1 and address2 are missing.

Also, if you check the DB  those fields are missing. #2785 was 11 days ago, and I pulled Bagisto just a few days ago.

The issue is the ordering of array merging in 'gatherBillingAddress' method overwrites the address field with blanks.
```php
        $billingAddress = array_merge(
            $data['billing'],
            ['cart_id' => $cart->id],
            $this->fillCustomerAttributes(),
            $this->fillAddressAttributes($data['billing']),
            $customerAddress // moved it as last
        );
```
The order in array_merge can be tricky; perhaps each array should 'unset' it's own 'blank' fields to prevent nulling the existing values (unless that is the desired effect).

**Comment by rahulcs0082** [comment] 2020-05-14 09:37
Hi @SpareShade 

This issue has been fixed but we are not using address2 field anymore.

**Comment by vaishaliwebkul** [comment] 2020-05-20 09:48
Hi @SpareShade 
Hope, the issue is being resolved now.

We are closing the issue, Feel free to reopen if still exist.

**Closed by vaishaliwebkul** 2020-05-20 09:48 UTC
