### ISSUE TITLE
Product images does not display, product attribute does not function properly (Version 1.2.0)

### ISSUE THREAD

**Issue by nextcart** [bagisto/bagisto#4753] opened 2021-03-23 02:38 UTC
# Bug report

### Title
Product images does not display, product attribute does not function properly (Bagisto 1.2.0).

### Issue Description
1. When I choose and upload images to the product in admin, the images displayed well. But after I click **Save Product**, all images disappear.
2. Product attribute has **Is Required** set to **No**, but when you create a new product, it always get and display the first value. You cannot hide the attribute except by deleting it.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1: Go edit a product from admin
    2. step2: Select and add an image
    3. step3: Click "Save Product"
    4. step4: View product in admin as well as in storefront again

### Expected result
Our team at Next-Cart is developing a migration tool to help people migrate their online stores to Bagisto. And it would be great if these issues are fixed in version 1.2.0.

### Actual result

>    The migration tool can cover these issues and bring our clients the expected results right after the migration is complete. But the clients won't be happy when they discover these issues on their Bagisto online store as they work on it.

**Comment by ghermans** [comment] 2021-03-23 02:45
Hi, thank you for reporting this issue, may i please ask you to verify if you experience the same issue with our latest version 1.3.1?

https://github.com/bagisto/bagisto/archive/refs/heads/master.zip

**Comment by nextcart** [comment] 2021-03-23 02:51
Hi Ghermans,

Thank you for your prompt response. We have used the version 1.2.0 as recommended by Saurav Pathak from your team. We will try the version 1.3.1 and let you know if the issues are solved.

Thank you!

**Comment by nextcart** [comment] 2021-03-23 03:08
Hi,

We are installing the 1.3.1 version, we got this error when running the command `composer install`:

> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Nothing to install, update or remove
> Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
> Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover
> 
> In ProviderRepository.php line 208:
> 
>   Class 'Webkul\Theme\Providers\ThemeServiceProvider' not found
> 
> 
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

You could try installing the official 1.3.1 version at: https://bagisto.com/en/download/.

Thank you!

**Comment by ghermans** [comment] 2021-03-23 03:19
hmm strange i just did a fresh clone and couldn't reproduce that error
I guess you are already following below steps, but just to be sure:

```
git clone https://github.com/bagisto/bagisto.git
composer install
php artisan bagisto:install
```

**Comment by devansh-webkul** [comment] 2021-03-24 05:30
Hi @ghermans and @nextcart,

This is not an issue there may be a linking problem,

Please try this,

https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions

**Comment by rahulshukla-webkul** [comment] 2021-03-24 11:46
Hi @nextcart 

We are closing this one as your issue as been resolved.
Feel free to open this.

**Closed by rahulshukla-webkul** 2021-03-24 11:46 UTC
