### ISSUE TITLE
Incorrect number of products display in cart if product already added in cart is deleted from back-end.Also showing incorrect price in this case, previous product price is also added.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#281] opened 2018-12-06 06:37 UTC
Framework Version : 0.1.2

Test Steps:
1. Add a product in cart.
2. Delete that product from back-end.
3. Refresh the cart page.

Result: Product will be removed by cart but count remains the same.
![screenshot 28](https://user-images.githubusercontent.com/45203177/49566119-8aba5500-f94f-11e8-9824-26d38daaaa06.png)

**Comment by prashant-webkul** [comment] 2018-12-19 10:37
This issue is marked as critical bug because it breaks up cart instance from its summary information to item information as items get deleted when the product is also deleted from the backend.

We are looking for possible solutions to tackle this issue and the best one will be applied soon.

As deleting the the products is a rare or an action done by mistake and this will prevent this situation form coming up again and again.

Possibly v0.1.4 will have the fix for this, we have left it out of release v0.1.3.

**Comment by prashant-webkul** [comment] 2019-01-29 09:36
Making this an duplicate of issue #368

**Closed by prashant-webkul** 2019-01-29 09:36 UTC
Labels: critical bug, shop
