### ISSUE TITLE
The catalog rule and cart rule have been successfully created; however, the applied discount is not reflecting on the shop. 

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9025] opened 2023-11-21 09:49 UTC
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The catalog rule and cart rule have been successfully created; however, the applied discount is not reflecting on the shop. 

### Preconditions

- Access the administrative panel and log in.
- Establish a catalog or cart rule.

### Steps to reproduce

- Go to 'admin panel'
- Create Catalog Rule, click on 'admin > marketing > promotions > catalog-rules > create catalog rule'.
- Visit the 'Shop,' observe that the discount is not being applied to the products.

### Expected Result

After the successful creation of catalog and cart rules, discounts should be applied to products according to the specified conditions. 

### Actual Result

The catalog rule and cart rule have been successfully created; however, the applied discount is not reflecting on the shop.

**Comment by ashishkumar-webkul** [comment] 2023-11-30 05:39
@sunarcrajneesh 

Checked and Found that the issue is invalid. I have applied both cart rule and catalog rule and they are working fine. Please check the screenshots below.

**CART RULE**

**Admin End - https://prnt.sc/ZGxN2CHfhZTe**
**Shop End - https://prnt.sc/4K3Z4hPMO_Kp** 

**CATALOG RULE**

**Admn End - https://prnt.sc/uLWx7hP9eq73**
**Shop End - https://prnt.sc/prkSA2iNenHO https://prnt.sc/5VeeKzTDz5-6   **

**Comment by ashishkumar-webkul** [comment] 2023-11-30 07:34
@sunarcrajneesh 

Can you please explain a bit more in which particular case you faced such issue. For now as I have checked and I did not find such issue.

**Comment by ramkishansuthar** [comment] 2023-12-04 11:41
Hi @ashishkumar-webkul, 

I am also facing the same issue with Bagisto 2. I have added a catalog rule and the rule is not applying. We did little debug and found that you fetched the product prices from product_price_indices table. In my case the this table still has the actual price. It should be as per applied catalog rule. 

Thanks

**Comment by ashishkumar-webkul** [comment] 2023-12-04 11:50
@ramkishansuthar 
Thanks you so much for the concern, we will check and update you accordingly.

**Comment by ramkishansuthar** [comment] 2023-12-11 07:09
Hi @ashishkumar-webkul,

Do you have any other updates on this?

**Comment by ramkishansuthar** [comment] 2023-12-12 11:22
Thank you @jitendra-webkul

**Comment by ramkishansuthar** [comment] 2023-12-12 12:38
Hi @jitendra-webkul 

I don't think this issue is fixed. Did you check it for new channel? I added a rule for a new channel (not default) and I am not getting updated price. I also run the indexer command in command line. 

Let me know if anything else needs to be done to get the updated price. 

Thanks

**Comment by jitendra-webkul** [comment] 2023-12-12 12:57
Can you run the following command

php artisan indexer:index --mode=full

**Comment by ramkishansuthar** [comment] 2023-12-12 13:09
It worked now. I didn't add --mode=full. I assume this is indexing with whole SKUs. Thanks for the help @jitendra-webkul. One last thing by when it will be added in the stable release?

**Comment by jitendra-webkul** [comment] 2023-12-12 13:28
Bagisto supports two indexing modes: **Full** and **Selective** (Default Mode).

The Selective mode specifically targets products with expiring prices, such as special prices. However, as of now, Selective mode doesn't integrate with catalog rules. We are actively working on a solution to make it compatible with catalog rules.

Anticipate the release of the new version by the end of this week or the beginning of next week."

**Comment by ashishkumar-webkul** [comment] 2023-12-13 06:33
Checked and Found that the issue has been fixed and working fine now. Hence I am closing this issue, please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/d7853111-8625-4feb-9a13-9f287420a5bd

**Closed by ashishkumar-webkul** 2023-12-13 06:33 UTC
Labels: Bug, QA Passed, Bug Fixed

**Comment by jitendra-webkul** [comment] 2023-12-13 08:04
With the recent update in PR #9134, the Selective indexer now seamlessly integrates with catalog rules.

Additionally, product price reindexing will occur automatically upon the creation, update, or deletion of a catalog rule. There is no longer a need to manually run the indexer command going forward.
